# Generated by Django 6.1 on 2026-09-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='driver_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
